### ISSUE TITLE
Parsing of duration/periods and converting them.

### ISSUE THREAD

**Issue by hura** [clj-time/clj-time#109]
Hi,

I've just had to parse a time duration and I don't think this functionality is implemented in clj-time.

I'd suggest to have a namespace like

```clj
(clj-time.duration/parse "<iso 8601 duration string>")
```

A few annoying facts for Joda time:

- Joda uses Period to mean what everybody else calls Duration.
- Duration/parse only works for seconds and ms and will fail for anything else.
- Period/parse will work for all ISO 8601 duration strings
- A Period object's (.getMillis) doesn't actually tell you the number of ms in that period. It only gets the MS of the period which would be 0 for a period of 5s.

```clj
(.getMillis (Duration/parse "PT5.32S")) ; 5320
(.getMillis (Period/parse "PT5.32S")) ; 320
; Adding 1 Day:
(Duration/parse "P1DT5.32S") ; error
(Period/parse "P1DT5.32S") ; works
; "workaround":
(.getMillis (.toStandardDuration (Period/parse "PT12H30M5.345S"))) ; 45005345
```

I'm not sure what's the best way to incorporate this into clj-time? Just figured I'd drop it here for now.

Cheers

**Comment by seancorfield** [comment]
I have no idea what the action should be here. Is this really a need that many users have?

**Comment by hura** [comment]
I'd say it's quite common (but maybe the lack of issues here say I'm wrong) to need a duration. Think of timeouts or triggers etc..

I needed this to do something like this in an EDN:
```
:timeouts {
  ; Timeout for running hook scripts. After this timeout the scripts will be killed!
  :hooks #period "1s"
  ; Elasticsearch timeout for any queries etc.
  :es #period "2s"
}
```

**Comment by seancorfield** [comment]
Given that you have a workaround and no one else has commented in two and a half years, I'm going to close this due to lack of interest / input from the community.

**Comment by joelittlejohn** [comment]
Note for others:

If you don't need to add this as an edn reader, and you don't want to correct errors in the input (like @hura is doing above), parsing an ISO 8601 duration and working with clj-time is as easy as:

```clj
(ns foo
  (:require [clj-time.core :as time])
  (:import org.joda.time.Period))

(some-> myduration Period/parse time/in-seconds)
```
