### ISSUE TITLE
Tagged reader literal for org.joda.time.DateTimes

### ISSUE THREAD

**Issue by james-henderson** [clj-time/clj-time#113]
I'm conscious that there's already a related issue (#93) asking to support the `#inst` literal, but I think this is different enough to warrant a separate issue!

Would it be preferable to serialise o.j.t.DateTimes with a different tag - e.g. `#joda/date-time`, `#clj-time/date-time` or equivalent? This would mean that they'd be correctly de-serialised back to DateTimes rather than j.u.Dates.

It'd be quite a simple change - the addition of a `print-dup` defmethod and a small `data_readers.clj` file, but would have the benefit that users of clj-time wouldn't ever have to worry about manually serialising DateTimes, or (as seems to be quite common in code that I come across) using Joda times in some parts of an application and conversions to/from j.u.Dates in other parts where serialisation is required.

Happy to submit a PR if you're ok with the approach. Likewise, if I'm doing something wrong in my usage of clj-time, please let me know!

Thanks for a really useful library :)

James

**Comment by seancorfield** [comment]
If no one is willing to provide a PR after nearly a year, I vote to close this.

**Comment by james-henderson** [comment]
Yep, fine by me - I tend to convert them to `#inst`'s using the coerce namespace now anyway :)

James

**Comment by james-henderson** [comment]
(re-opening just so that someone on the project team can close, if you want to keep it open)
