### ISSUE TITLE
Please support custom format-local-time formats

### ISSUE THREAD

**Issue by johnjelinek** [clj-time/clj-time#131]
Right now, I have to provide an existing key to customize the format for local-now:

`(time-local/format-local-time (time-local/local-now) :date)`

I would like to provide a custom format.

**Comment by matevarga** [comment]
Further question: is there a reason why to-local-date-time returns a DateTime object and not a LocalDateTime object? parse-local returns a LocalDateTime. This  seems to be slightly inconsistent to me -- any reasons behind this?

**Comment by matevarga** [comment]
Ah, I see the problem now. Basically the meaning of 'local' in the .local namespace is that those functions handle DateTime objects (with time zones) in the local time zone, while LocalDateTime is timezone-less DateTime. This is not 100% clear from the naming/docs, so it'd worth to communicate that somewhere.

**Comment by seancorfield** [comment]
Seems like this issue is "closed" but we need a doc update? I vote to close this and encourage a PR on the docs.

**Comment by seancorfield** [comment]
@matevarga Do you have a suggestion on how to improve the documentation to make that clearer? PR welcome.

Meanwhile I'm closing this since the original question was answered, do you agree @johnjelinek ?
