### ISSUE TITLE
Date sequence for "end of month"

### ISSUE THREAD

**Issue by michaelklishin** [clj-time/clj-time#137]
Reported in #130: when `periodic-seq` is used with an interval of `(months 1)`, it is not clear what the expectations are:

 * A step of every 30 days
 * A step that produces "last day of the month" for the next month

We need to clarify this in the docs and perhaps add another function for "last day of month".

**Comment by seancorfield** [comment]
Does that commit fix this issue?

**Comment by seancorfield** [comment]
I updated the README to clarify the behavior so I'm closing this.
