### ISSUE TITLE
Cut a new release?

### ISSUE THREAD

**Issue by danielcompton** [clj-time/clj-time#186]
There are some fixes, particularly https://github.com/clj-time/clj-time/pull/162 that we'd like to have, but there isn't a new release with these in.

Are you able to make a new release?

**Comment by michaelklishin** [comment]
Will do one before Monday.

**Comment by theikkila** [comment]
Would it be this Monday?

**Comment by michaelklishin** [comment]
Sorry, this fell off from my radar, will do a release in a few hours.

**Comment by theikkila** [comment]
Cool, let me know when it's online!

**Comment by michaelklishin** [comment]
`0.10.0` is up on Clojars.
