### ISSUE TITLE
Dependencies out of date

### ISSUE THREAD

**Issue by rwilson** [clj-time/clj-time#190]
To use Java 1.8u60 requires joda time 2.8.1, which is included implicitly as long as the dependency graph doesn't _explicitly_ pull in a different version. Declaring a dependency on clj-time 0.10.0 pulls in joda time 2.7, as shown by `lein deps :tree`:

```bash
[clj-time "0.10.0"]
   [joda-time "2.7"]
```

See: https://github.com/aws/aws-sdk-java/issues/484 for one manifestation, an AWS authentication error from an incompatibility in Java 1.8u60 w/ joda time 2.7. I hit this error as well, in a project using clj-time 0.10.0 with a docker image based on "java:8". That's my fault for not explicitly targeting java:8u45, but I didn't realize it because when I first did it "java:8" was equivalent to "java:8u45", and it surprised me by breaking one day when java:8 was no longer java:8u45.

**Comment by michaelklishin** [comment]
`0.11.0` depends on Joda Time `2.8.2`.

**Comment by rwilson** [comment]
Thanks for the quick fix!
