### ISSUE TITLE
Bug in today-at?

### ISSUE THREAD

**Issue by dgr** [clj-time/clj-time#191]
I think there's a pseudo-bug in `today-at`. I say pseudo-bug because perhaps it's valid, but it's entirely unexpected.

The problem is that "today" is ambiguous with respect to time zone. You can see this behavior if you call `today-at` in a time zone that is a negative offset from UTC (say the USA) after UTC has rolled over to the following day (say in the late evening, local time, perhaps 23:00 local time in any USA timezone), you end up with a returned value that is quite unexpected, where "today" is actually tomorrow. If you call `today-at` _before midnight UTC_, you'll get a value that has the right date and time values for both the local time zone and UTC, but the time zone is specified as UTC. You can adjust that value with `from-time-zone` to the local time zone and you're good to go. But not so _after midnight UTC_ since the date will be one day ahead. This means that to use `today-at` as it currently stands, you really must think in terms of UTC at all times, specifying the right time value _in UTC_ and then using `to-time-zone` to adjust things that way. And that completely negates the usability of `today-at`, IMO. In other words, `today-at` should more rightly be named `today-at-utc`.

There are two solutions I can think of:
1. Modify today-at so that it always works in the `default-time-zone`. It returns a date-time value in the local zone.
2. Create a new function, say `today-at-timezone`, that adds a time-zone argument. When `today-at` generates the current time with `(now)` to get its idea of "today," the function would adjust that to the right timezone using `to-time-zone` and then stuff in the hour, minute, and second values. Effectively, solution 1 would be `(today-at-timezone hour minute second (default-time-zone))`. That would allow you to get the right idea of "today" even in a remote time zone.

Does that make sense?

**Comment by seancorfield** [comment]
My feeling is that clj-time is primarily a UTC-based library and so the core functions should all be expected to work "in UTC" (and then you convert to whatever timezone you want, if applicable). In my production applications, all our servers are set to UTC and NTP-synced, and our databases are also set to UTC internally.

That said, I think `today-at` is a fairly strange function and I've never had to use it so I don't feel strongly about its behavior.

**Comment by dgr** [comment]
I hear ya. That said, there are many domains that operate in local time. Capital markets in New York, for instance, close at 4pm local time, regardless of daylight savings time adjustments. It would be nice to say `(today-at 4 0)` when operating in US Eastern Time, or `(today-at 4 0 (time-zone-for-id "America/New York")`,  to specify such a time. I don't mind, for instance, that `date-time` returns a date/time in UTC, for instance. But then you have `to-time-zone` and `from-time-zone` to adjust appropriately. But there's no easy way to do that. You basically have to rewrite `today-at` in your own code to do what you would expect it to do.

I'm cool either rewriting it in my own code or I could submit a patch with whichever behavior you want (though there's probably an issue with backwards compatibility if you go with solution 1 that I proposed, "correcting" it to work in the default time zone).

I suggest, however, that if you want to leave it alone, you add a documentation string for it that accurately specifies its behavior. The docs in the README.md are also ambiguous.

**Comment by dgr** [comment]
Interestingly, the `today` function returns a `LocalDate` which is "today" in the local time zone (i.e., not in UTC). Thus, you have the case where the dates returned by `today` and `today-at` are different if the date in the local time zone differs from the date in UTC.

**Comment by dgr** [comment]
For instance, I'm playing at the REPL about 15 minutes before midnight, USA Central Time.
```
xyz.core=> (t/today)
#object[org.joda.time.LocalDate 0x234bad54 "2015-08-13"]
xyz.core=> (t/today-at 10 00)
#object[org.joda.time.DateTime 0x148ea110 "2015-08-14T10:00:00.000Z"]
```

**Comment by dgr** [comment]
And, `today-at-midnight` takes a time zone as a parameter. If you don't supply one, it assumes UTC. This is how I think `today-at` should probably work:
```
xyz.core=> (t/today-at-midnight)
#object[org.joda.time.DateMidnight 0x3e8febbc "2015-08-14T00:00:00.000Z"]
xyz.core=> (t/today-at-midnight (t/default-time-zone))
#object[org.joda.time.DateMidnight 0x29fb9c4d "2015-08-13T00:00:00.000-05:00"]
```

**Comment by dgr** [comment]
One would expect that `(= (today-at-midnight) (today-at 0 0))` would be true, which it is. But what about `(= (today-at-midnight (default-time-zone)) (today-at 0 0))` ? There's no `(today-at 0 0 (default-time-zone))` to go with `(today-at-midnight (default-time-zone))`.

**Comment by seancorfield** [comment]
This is all great feedback. I agree that `today-at` is not producing intuitive results. Your comparison with `today-at-midnight` is compelling. You're convincing me that an optional timezone argument is a good solution. @michaelklishin do you have input on this?

**Comment by dgr** [comment]
Was thinking about this more last night. The fundamental issue, I think, is that "today" as a word is a relative human concept. It's a rather ill-specified word for humans in general. It's always interpreted relative to some context, the context of the speaker. In the clj-time API, the word "today" is treated inconsistently, sometimes as relative to UTC (`today-at`), sometimes as relative to the local time zone (`today`), and sometimes relative to either, depending on parameters (`today-at-midnight`). For the benefit of application developers using the API, the API should choose a consistent meaning for `today`. Always relative to UTC is one possible choice, though because "today" is a relative concept in human speech, I think that's a sub-optimal choice. The right answer is probably to allow for an optional time zone in all of the various "today" functions, consistently defaulting to either UTC or `default-time-zone` if no specific time zone is specified. That would mean adding time zone parameters to both `today` and `today-at`; `today-at-midnight` is already good to go.

**Comment by dgr** [comment]
BTW, you could probably implement this by first fixing `today` and then using it as the basis of `today-at`, which then forms the basis of `today-at-midnight`. That would help ensure consistency throughout.

**Comment by seancorfield** [comment]
@michaelklishin Did you have any feedback on this? I find @dgr's argument compelling but I don't see how to make the defaults consistent in a backward compatible manner. Perhaps something needs to be deprecated here?

**Comment by seancorfield** [comment]
The docstring for `today-at` and README have been updated so I am closing this. We'll still entertain a PR for _additional_ functionality.
