### ISSUE TITLE
t/days doc misleading or bug?

### ISSUE THREAD

**Issue by mjg123** [clj-time/clj-time#192]
According to https://clj-time.github.io/clj-time/doc/clj-time.core.html#var-days :

```
(days n)
  Given a number, returns a Period representing that many days.
```

But actually it only works with integers.  I was hoping to be able to use:

```
(t/in-hours (t/days 0.5))
=> 12
```

But this actually returns zero.  Unless I missed another helper fn, this means I have to do my own arithmatic to convert partial days to hours/minutes/etc, which is a shame as I'd hope there's a nice clojure-time library to do that.

I guess this might be as simple as a doc change `s/number/integer/` ? or do you think we should support fractional days? Or another helper function?

**Comment by michaelklishin** [comment]
Joda Time tries hard to avoid floats in the API because calculations with floats are imprecise. See [Period](http://joda-time.sourceforge.net/apidocs/org/joda/time/Period.html), for example.

So instead of "0.5 days" you have to use 12 hours.

**Comment by mjg123** [comment]
Fair enough. I have to do my own imprecise float calculations before I can call clj-time.  Would you be interested in a PR which created a new ns like `clj-time.imprecise` with fns like `float-days-to-period`?  I could spend some time on it if you are.

**Comment by seancorfield** [comment]
I would not be in favor of such a namespace. I view time as a set of precise units -- and at odds with doing imprecise math (and certainly not `float`-anything, given Clojure's defaults of `long` and `double`).

**Comment by mjg123** [comment]
OK thanks for replying Sean.
