### ISSUE TITLE
Travis fails for openjdk6 due to lack of ForkJoin

### ISSUE THREAD

**Issue by seancorfield** [clj-time/clj-time#199]
In the latest round of changes to update dependencies, I seem to have introduced a dependency on ForkJoin / reducers and thus the build fails on openjdk6 (unless we add the jsr66y dependency).

Given how long ago Java 6 hit EOL, I'm inclined to just drop it from the test matrix and let folks who run into this exception deal with the dependency themselves:

Exception in thread "main" java.lang.ClassNotFoundException: jsr166y.ForkJoinPool, compiling:(clojure/core/reducers.clj:56:21)

**Comment by michaelklishin** [comment]
Done in https://github.com/clj-time/clj-time/commit/36ff9870ae67703bfe50e44406a73bd238a6100a (and I completely agree).
