### ISSUE TITLE
use .withTimeAtStartOfDay() instead of DateMidnight

### ISSUE THREAD

**Issue by echeran** [clj-time/clj-time#201]
According to the docs, given a DateTime, to get the beginning of a day, we should use .withTimeAtStartOfDay() -- see http://www.joda.org/joda-time/apidocs/org/joda/time/DateMidnight.html .  General practice also confirms -- http://stackoverflow.com/questions/17665921/recommended-use-for-joda-times-datemidnight

So, a couple of options are: 1) deprecate clj-time.core/today-at-midnight and introduce with with-time-at-start-of-day;  2) change the implementation of today-at-midnight

Option #1 seems cleaner as it tracks the evolution that was required in joda-time.

**Comment by michaelklishin** [comment]
@echeran I like option 1 better. @seancorfield, what do you think?

**Comment by seancorfield** [comment]
:+1: for option 1.
