### ISSUE TITLE
Durations are type hinted with Integer instead of Long.

### ISSUE THREAD

**Issue by j-pb** [clj-time/clj-time#203]
Even though joda itself expects longs to instantiate it's Period, clj-time functions like `clj-time.core/millis` expect an Integer.
This results in failure to convert even basic (sub month long) durations from milliseconds.

```
IllegalArgumentException Value out of range for int: 2421314175  clojure.lang.RT.intCast (RT.java:1191)
```

**Comment by michaelklishin** [comment]
@j-pb please submit a PR?

**Comment by j-pb** [comment]
On it :)

**Comment by seancorfield** [comment]
@j-pb Any PR forthcoming or shall I just close this?

**Comment by firesofmay** [comment]
Hi, I was looking to fix this issue.
But from the documentation here - http://www.joda.org/joda-time/apidocs/org/joda/time/Period.html#millis-int- for millis function, it does take integer.
Am I looking at the wrong function to fix here?

```
(defn millis
  "Given a number, returns a Period representing that many milliseconds.
   Without an argument, returns a PeriodType representing only milliseconds."
  ([]
     (PeriodType/millis))
  ([^Long n]
     (Period/millis n)))
```

This is the change I thought was being discussed here, but this looks incorrect.
Please guide me on what is the correct fix here.
Thanks.

**Comment by michaelklishin** [comment]
@firesofmay It could be something introduced only in a recent Joda Time version.

**Comment by firesofmay** [comment]
@michaelklishin Ack, guess this issue can be closed then.
