### ISSUE TITLE
Consider adding predicates like date-time?, local-date-time?, date?, etc.

### ISSUE THREAD

**Issue by pangloss** [clj-time/clj-time#220]
I find myself needing these types of predicates periodically and each time I spend a bunch of time trying to find them in the project before realizing they're not there before giving up and implementing them in my own project.

Is there a reason these aren't present in the project? If not I'm happy to provide a patch.

Thanks,
Darrick

**Comment by seancorfield** [comment]
I'm curious, what is the use case that causes you to need these? (I've never needed them and consider type-based predicates to be a bit of a code smell)

**Comment by pangloss** [comment]
In one place, I recently needed them for some clojure.spec declarations. In another I needed it for a web service endpoint where the data can come in either from transit (in which case it's already the correct type), and in the other it comes from JSON and needs to be coerced. I also want to make guarantees that I'm getting a DateTime vs a Date in that situation, so type checking is required there as well.

**Comment by seancorfield** [comment]
Interesting. I'm not hugely against adding them but bear in mind that we're discussing a shift in implementation from Joda Time to Java 8's new JSR-310 Time library -- see https://github.com/clj-time/clj-time/issues/196 -- so that might impact any such predicates (as the underlying Java types would change).

**Comment by pangloss** [comment]
I think that having the predicates in the library makes this easier as it locates the detail of which class represents a date-time, etc within the library itself. The predicates are simple one-liners so I don't see them presenting any problem in general.

**Comment by seancorfield** [comment]
Happy to consider a Pull Request then.

**Comment by drusellers** [comment]
With Clojure Spec on the horizon I would love to see this happen

**Comment by firesofmay** [comment]
@seancorfield Is this still something you would consider adding? If yes I would like to add these fns. Also in which ns you would like to add them to, clj-time.core?

**Comment by michaelklishin** [comment]
They can be useful. I'd introduce `clj-time.types`.

**Comment by firesofmay** [comment]
@michaelklishin I see that there is already a pull reuqest for this fix - https://github.com/clj-time/clj-time/pull/229
Is there a reason we haven't merged it yet? I don't see any conversation on that thread.

**Comment by seancorfield** [comment]
The existing PR seems to have a number of unresolved issues and, as noted above, I don't really think it's a good idea. Per @michaelklishin they probably need to go in a separate ns, and the timezone stuff needs to be figured out.

**Comment by pangloss** [comment]
Hi Sean,

In the PR, everything is actually in a separate ns.

As to the "unresolved issues" relating to time zones, that is very much an edge case only affecting users who expect to do generative testing on functions where they expect to call the function with datetimes each set at random different time zones. The only reason that it's unresolved is that I couldn't figure out how to get clj-time or JodaTime to produce datetimes with a specified timezone! Perhaps it's impossible to even do that, in which case we could hardly consider that an unresolved testing issue!

Otherwise I believe #229 is ready to be merged.

Regards,
Darrick

**Comment by seancorfield** [comment]
It's merged and part of 0.14.0.
