### ISSUE TITLE
within? returns different results based on the number of arguments

### ISSUE THREAD

**Issue by omartell** [clj-time/clj-time#222]
The following results from `within?` tripped me up a little bit:

```clojure
(time/within? (time/interval (time/date-time 2016 11 18) 
                             (time/date-time 2016 11 22))
              (time/date-time 2016 11 22)) ;; => false

(time/within? (time/date-time 2016 11 18)
              (time/date-time 2016 11 22)
              (time/date-time 2016 11 22)) ;; => true
```

Shouldn't the API be consistent in both cases? Just a thought.

**Comment by seancorfield** [comment]
The docstring is very clear about this behavior, and it's precisely this that allows users to control whether they want an inclusive test (three arguments) or exclusive test (two arguments, with an interval).
