### ISSUE TITLE
Upgrade to JodaTime 2.9.7

### ISSUE THREAD

**Issue by michaelklishin** [clj-time/clj-time#223]
[Release notes](https://github.com/JodaOrg/joda-time/releases/tag/v2.9.7).

**Comment by seancorfield** [comment]
Sounds good. We'll cut 0.13.0 with this in?

**Comment by michaelklishin** [comment]
@seancorfield 👍

**Comment by seancorfield** [comment]
https://clojars.org/clj-time/versions/0.13.0

**Comment by michaelklishin** [comment]
@seancorfield thank you!
