### ISSUE TITLE
How does timezone work?

### ISSUE THREAD

**Issue by Freyr666** [clj-time/clj-time#228]
For example I'm converting some string to long with the `clj-time.coerce/to-long` call

```
(clj-time.coerce/to-long "2017-02-07T10:46:00.000+03:00")
```

which gives 1486453560000

And i have a function supposed to format time values in a long representation such as

```
(defn format-long-date [date zone]
  (let [dt (time-conv/from-long date)]
    (let [dtz (if (nil? zone)
                dt
                (time-core/to-time-zone dt zone))]
      (time-format/unparse (clj-time.format/formatter "d MMMM, yyyy H:m:s (z)") dtz))))
```

But it seems that `time-core/to-time-zone` does not apply timezone at all so this function returns utc value:

>(format-long-date 
         (clj-time.coerce/to-long "2017-02-07T10:46:00.000+03:00")
         (clj-time.core/time-zone-for-id "+03:00"))
"7 February, 2017 7:46:0 (UTC)"

If I change time-core/to-time-zone with time-core/from-time-zone `format-long-date` returns "7 February, 2017 4:46:0 (UTC)"

How could I deal with timezones properly in my case?

**Comment by Freyr666** [comment]
It seems that 
```
(clj-time.core/to-time-zone (clj-time.coerce/to-date-time "2017-02-07T10:46:00.000+03:00")
                                           (clj-time.core/time-zone-for-id "+03:00"))
```
works as expected and returns 
#object[org.joda.time.DateTime 0x685d20cf "2017-02-07T10:46:00.000+03:00"]

It seems that both `to-string` and `format` ignore timezones. How could i convert date-time to string value in proper format?

**Comment by Freyr666** [comment]
Ok, I found the way to do so. It seems i have to build a zoned formatter with `(time-format/with-zone formatter zone)`. Such an unobvious way of formatting date-time value.

**Comment by seancorfield** [comment]
Glad you figured it out. Closing this (but if you want to send a PR for the readme / docs with improvements, that's always appreciated).
