### ISSUE TITLE
Please mention about JDBC converting times in docs somewhere

### ISSUE THREAD

**Issue by freckletonj** [clj-time/clj-time#233]
**Solution**: `:jvm-opts ["-Duser.timezone=UTC"]` in `project.clj`

I just killed an hour or two trying to figure out why my database _seemed_ to have UTCs, but then when I `SELECT` a `datetime`, somehow it's... `local`?

_Note_: This isn't `clj-time`'s fault, but documentation here would probably help since this lib seems to be the common denominator in all things clojure-time related.

This is what I just had to go through:

1. Is my code coercing things inappropriately? hm, no.

2. Is my mysql code? no.

3. Is it YeSQL? no.

4. Is it `clj-time`? well, no, but that's what I use for all my times...

5. Maybe it's `clj-time`'s upstream, `joda-time`? no...

6. Something about `java.util.Date`? not really

7. Am I _sure_ the times are saved one way and showing up another? ya....

8. Hm, let me try every function in `coerce` to see if I can get it back to UTC. Not unless I convert timezones, that's not reliable unless I configure for every box I might have this deployed on...

9. Finally, this SO thread: http://stackoverflow.com/questions/25123054/timezone-issues-with-mysql-and-clj-time . Seemed so farfetched, why do I have to configure the JVM to read UTCs as UTCs?

Oh, that was it.

Times are frustrating as it is, and this is in _no_ way `clj-time`'s fault, so, sorry to vent. But I'm hoping that in writing this up I'll hit a couple keywords other people might be searching for :)

**Comment by michaelklishin** [comment]
Feel free to submit a PR.

**Comment by seancorfield** [comment]
This is why it's important to have all servers and database software set to UTC, and time-sync'd via NTP, in production. Note that with MySQL, you often have to configure UTC for the database _in addition_ to setting the underlying server to UTC.

**Comment by seancorfield** [comment]
On the basis that this issue is _not_ `clj-time's "fault" and it crops up for all sorts of time-related issues around UTC -- because folks don't follow best practice of "UTC everywhere" -- I'm closing this. As @michaelklishin said, @freckletonj, feel free to submit a PR against the readme or the docs.

**Comment by neilcode** [comment]
Just spent a few hours on this same issue myself. I echo @freckletonj  thoughts on the matter that while its not really an issue with `clj-time`, it's such an obnoxious gotcha that an entry in the project README would probably be helpful. Submitting a PR.

**Comment by michaelklishin** [comment]
@neilcode you haven't provided much details to work with. We have never limited PRs in any way, in fact, I don't think there is a way to do that on GitHub.

**Comment by michaelklishin** [comment]
This repo technically is a fork, so pay attention to what base branch/fork you choose when submitting a PR. Otherwise it should be as easy as editing the file on GitHub and then choosing this fork as the base.
