### ISSUE TITLE
Must Import DateTime after upgrade to 0.14.1

### ISSUE THREAD

**Issue by zerg000000** [clj-time/clj-time#241]
don't know if this is a breaking change.

before 0.14.1

this code could be compiled and run without importing Joda DateTime class
```{clojure}
(require '[clj-time.coerce :as tc])
(-> (tc/to-date-time 1)
    .toLocalTime)
```
after 0.14.1, exception will throw

```{clojure}
CompilerException java.lang.IllegalArgumentException: Unable to resolve classname: DateTime, compiling:
```

**Comment by seancorfield** [comment]
Ah, sorry, the type hints need to be fully-qualified to solve this. I'll get that fixed today and put 0.14.2 out.

**Comment by seancorfield** [comment]
Release 0.14.2 is available on Clojars and should fix this. Sorry for the inconvenience -- and thank you for finding and reporting this so quickly!

**Comment by zerg000000** [comment]
Thanks for you amazing quick respond.
