### ISSUE TITLE
Update dependencies

### ISSUE THREAD

**Issue by seancorfield** [clj-time/clj-time#242]
Joda Time 2.9.9, Java JDBC 0.7.3.

http://www.joda.org/joda-time/changes-report.html

Very minor changes since 2.9.7 so no rush for this.

**Comment by atroche** [comment]
Looks like this is fixed in https://github.com/clj-time/clj-time/commit/e7ee35275368d4aebc4cf9bbfdbc3ce4497f2272 :)
