### ISSUE TITLE
unparsing a nil datetime unparses now

### ISSUE THREAD

**Issue by Heliosmaster** [clj-time/clj-time#245]
```clj
(time-format/unparse (time-format/formatter "dd/MM/yyyy HH:mm") nil)
```

is equivalent to 

```clj
(time-format/unparse (time-format/formatter "dd/MM/yyyy HH:mm") (time/now))
```

This behavior is somewhat unexpected, as I would imagine the function to throw an error about printing nil datetimes.

**Comment by seancorfield** [comment]
I agree it is somewhat surprising, but that is the behavior of Joda Time's `DateTimeFormatter/print` function apparently (since `(.print fmt dt)` is all `unparse` does).
