### ISSUE TITLE
Year from an instant gets mis-parsed: 2018 becomes 118

### ISSUE THREAD

**Issue by WorldsEndless** [clj-time/clj-time#246]
```
(timec/year (timec/from-utc-time-zone (js/Date.)))
118
```

**Comment by seancorfield** [comment]
What is `js/Date.`? `clj-time` is a Clojure/JVM-only library, based on Joda Time. Was this meant to be an issue for https://github.com/andrewmcveigh/cljs-time instead?

**Comment by WorldsEndless** [comment]
Ah! Indeed I did. I had both pages open. My mistake
