### ISSUE TITLE
Extend Inst protocol to org.joda.time.DateTime

### ISSUE THREAD

**Issue by glts** [clj-time/clj-time#248]
Clojure 1.9 introduced the `Inst` protocol and with it the predicate `inst?` and the accessor/conversion operation `inst-ms`.

Out of the box, `Inst` is extended to `java.util.Date` and, on Java 8 and later, to `java.time.Instant`.

```clojure
(inst? (java.util.Date.))        ;; => true
(inst? (java.time.Instant/now))  ;; => true
(inst? (clj-time.core/now))      ;; => false
```

Please consider extending the `Inst` protocol to `org.joda.time.DateTime` on Clojure 1.9 and later. This would help improve interoperability and using insts more independently of the concrete implementation. Since clj-time in some sense has a de facto ‘ownership’ of `org.joda.time.DateTime` in the Clojure library world, I believe you are best suited to do such a protocol extension.

Thank you!

**Comment by seancorfield** [comment]
Sounds reasonable. PR, with tests, welcome.

Note: if you're on Java 8 or later, you should consider migrating from Joda Time/clj-time to Java Time (and, perhaps, clojure.java-time if you want a wrapper library).
