### ISSUE TITLE
No way to work with Periods & Durations

### ISSUE THREAD

**Issue by ignorabilis** [clj-time/clj-time#251]
As of now there seems to be no way to work with `Period` and `Duration`, which are part of `org.joda.time`. A good enough solution would be to add some multi arity functions, similar to `^org.joda.time.LocalTime local-time`.

**Comment by seancorfield** [comment]
PR welcome -- but bear in mind that Joda Time is pretty much deprecated in favor of using Java Time (as of Java 8) and we are encouraging folks to switch to either Java Time (and interop) or a wrapper like [clojure.java-time](https://github.com/dm3/clojure.java-time).

**Comment by seancorfield** [comment]
It's been a year, closing this.
