### ISSUE TITLE
Interval arithmetic

### ISSUE THREAD

**Issue by reutsharabani** [clj-time/clj-time#257]
Is it a good idea to add support for operations like `(plus (interval start end) (days 1))`?

It can simplify code when looking at time frames.

**Comment by seancorfield** [comment]
I don't think I'd want to reuse `plus` (or `minus`) here to operate on intervals. We have a `DateTimeProtocol` that declares `plus-` and `minus-` and then we have "global" `plus` and `minus` that reduce based on those protocol-based functions.

I will add an `adjust` function that takes one or more `ReadablePeriod` values that shifts the interval forward (or backward) by that amount.

**Comment by seancorfield** [comment]
Released as 0.15.1
