### ISSUE TITLE
no way to retain timezone information when parsing string

### ISSUE THREAD

**Issue by jasonsross** [clj-time/clj-time#272]
I can find no combination of parse, parse-local or formatter that will convert a string with timezone to a datetime with timezone offset still preserved such as "2020/01/22 12:00:00 +0600" going to `#object[org.joda.time.DateTime 0x3288b318 "2020-01-22T12:00:00+06:00"]`

```
(f/parse (f/formatter "yyyy/MM/dd HH:mm:ss Z") "2020/01/22 12:00:00 +0600")
#object[org.joda.time.DateTime 0x3288b318 "2020-01-22T06:00:00.000Z"]
-> seems to use the timezone to get UTC time correctly, but now I don't know what original timezone was.

(f/parse-local (f/formatter "yyyy/MM/dd HH:mm:ss Z") "2020/01/22 12:00:00 +0600")
#object[org.joda.time.LocalDateTime 0x547442d3 "2020-01-22T12:00:00.000"]
-> just ignores timezone

(f/parse (f/formatter-local "yyyy/MM/dd HH:mm:ss Z") "2020/01/22 12:00:00 +0600")
#object[org.joda.time.DateTime 0x524a59c1 "2020-01-22T00:00:00.000-06:00"]
-> I'm in -0600 timezone so I think formatter-local uses that plus the UTC offset of parse to get this result...

(f/parse-local (f/formatter-local "yyyy/MM/dd HH:mm:ss Z") "2020/01/22 12:00:00 +0600")
#object[org.joda.time.LocalDateTime 0x41f21bca "2020-01-22T12:00:00.000"]
-> parse-local cancels out the format-local functionality and just ignores timezone again.
```

the format-local is the most bizarre. How can I get a datetime object that matches the string as written preserving the timezone?

**Comment by seancorfield** [comment]
Joda Time is deprecated, as is clj-time, so I would suggest you look at parsing and formatting with Java Time directly and see whether you can solve your problem there. If there's currently no way to do this in clj-time, it is not a feature that will be added at this point, sorry.
