### ISSUE TITLE
truncate function

### ISSUE THREAD

**Issue by zcaudate** [clj-time/clj-time#36]
There can be a function for truncation... i had to write my own for getting rid of the ms and it looks ugly, especially if the time has to be in local time:

    (defn truncate-ms [dt]
       (t/to-time-zone
       (apply t/date-time
              (map #(% dt)
                   [t/year t/month t/day t/hour t/minute t/sec]))
       (t/default-time-zone)))

something in the library that can work like this would be nice:

    (truncate (local-now) days)

**Comment by timothypratley** [comment]
:+1:

**Comment by seancorfield** [comment]
PR welcome!

**Comment by Charlesetc** [comment]
Isn't this what the `floor` function does?

**Comment by seancorfield** [comment]
Closing as this seems to be what `floor` already does.
