### ISSUE TITLE
Why was "Duration" support removed?

### ISSUE THREAD

**Issue by mattias-lundell** [clj-time/clj-time#77]
Early in the beginning there was support for "Duration" but this was removed almost immediately. Any specific reason? Otherwise I propose that it should be added again.

**Comment by seancorfield** [comment]
Still open to PRs to restore this functionality in `clj-time.duration`...

**Comment by mattias-lundell** [comment]
I think I have started somewhere already. I will wrap it up in a PR.

**Comment by seancorfield** [comment]
Closing this In favor of a potential future PR.
