### ISSUE TITLE
Misleading doc string or bug?

### ISSUE THREAD

**Issue by ebaxt** [clj-time/clj-time#78]
Found a bug in wait-for: https://github.com/circleci/wait-for/pull/2

It was caused by trying to call . toStandardSeconds on the instance returned by `(clj-time.core/secs 1)`. 

According to the doc string this should return an instance of Period:

```clojure
(defn secs
  "Given a number, returns a Period representing that many seconds.
   Without an argument, returns a PeriodType representing only seconds."
  ([]
     (PeriodType/seconds))
  ([#^Integer n]
     (Seconds/seconds n)))
```

Shouldn't the last line be:

```clojure
(Period/seconds n)
```

From an api perspective that would make sense, since it would allow users to specify a period in there preferred time unit like in the wait-for library? 

```clojure
(wait-for {:sleep (time/secs 1)} ...)

(wait-for {:sleep (time/hours 1)} ...)
```

The same pattern can be found in weeks, months, hours etc. so maybe there is a good reason for this?

**Comment by seancorfield** [comment]
Still no PR to fix this? I'm inclined to close it as "no public use case" at this point.

**Comment by seancorfield** [comment]
Closing since this seems "resolved". We'll entertain a PR to improve the documentation / docstrings.
