### ISSUE TITLE
Add support for any-field periods

### ISSUE THREAD

**Issue by nybbles** [clj-time/clj-time#92]
This patch added support for single-field periods: https://github.com/clj-time/clj-time/commit/adc2d294c79560e1ce4411c3fc1a5a8582418a30.

I have to represent "7 hours and 30 minutes" as a period. Therefore, I'd like to add support for any-field periods, described here: http://joda-time.sourceforge.net/key_period.html.

This should just involve exposing the appropriate constructors found in [the javadoc for `Period`](http://joda-time.sourceforge.net/apidocs/org/joda/time/Period.html).

I wouldn't mind writing the code myself. Is this something that the maintainers would be open to merging?

**Comment by seancorfield** [comment]
Given that we're now three years on with no PR and no elaboration of the API, I'm closing this.
