### ISSUE TITLE
Let `formatter` accept formatters (and/or keywords)

### ISSUE THREAD

**Issue by leifp** [clj-time/clj-time#96]
This is an enhancement.

When writing formatters that accept several formats:

```clojure
;; I'd like to write:
(formatter (formatters :year-month-day)))
;; => ClassCastException org.joda.time.format.DateTimeFormatter cannot
;; be cast to java.lang.String  clj-time.format/formatter

;; or even
(formatter :year-month-day) ; use built-in automatically

;; then I could say
(formatter (default-time-zone) :year-month-day :basic-date "YY/dd/MM")
```

The current code seems to try to avoid reflection, but I feel some is acceptable here, because hopefully a formatter will be constructed once and used many times.

**Comment by seancorfield** [comment]
This actually caught me out this evening. It would be much more convenient for `formatter` to accept a keyword and automatically look it up in `formatters` (and the same for `parser`/`parsers`). Thoughts?

**Comment by seancorfield** [comment]
`formatter` has accepted keywords (as well as strings) for quite some time. I've modified it to accept formatter objects as well.
