### ISSUE TITLE
rfc822 formatter is wrong

### ISSUE THREAD

**Issue by prozz** [clj-time/clj-time#97]
hello

here is some snippet using rfc822 formatter:

```
=> (parse (formatters :rfc822) "Wed, 20 Nov 2013 09:57:08 GMT")
IllegalArgumentException Invalid format: "Wed, 20 Nov 2013 09:57:08 GMT" is malformed at "GMT"  org.joda.time.format.DateTimeFormatter.parseDateTime (DateTimeFormatter.java:866)
=> (parse (formatters :rfc822) "Mon, 02 Dec 2013 22:16:42 +0000")
#<DateTime 2013-12-02T22:16:42.000Z>
```

according to rfc both dates should be ok. pls see rfc here: http://www.ietf.org/rfc/rfc0822.txt

grep for 5.1. then see zone section.

thanks for developing clj-time :)
regards!

**Comment by mnylen** [comment]
Sorry for reopening this issue, but couldn't this be fixed by first trying to parse `EEE, dd MMM yyyy HH:mm:ss z` and, if that fails, try `EEE, dd MMM yyyy HH:mm:ss Z`?
